/**
 * Ikon Lucide untuk bucket alokasi — tabungan, dana, tujuan finansial.
 * Semua nama harus ada di CATEGORY_ICON_MAP (categoryIconMap.js).
 */
export const ALLOCATION_ICON_NAMES = [
  'Award',
  'BadgeDollarSign',
  'Banknote',
  'BanknoteArrowDown',
  'BanknoteArrowUp',
  'Bitcoin',
  'Briefcase',
  'BriefcaseBusiness',
  'Building2',
  'Calculator',
  'Car',
  'ChartBar',
  'ChartLine',
  'ChartPie',
  'CircleDollarSign',
  'Coins',
  'Crown',
  'DollarSign',
  'FileSpreadsheet',
  'Gem',
  'Gift',
  'GraduationCap',
  'HandCoins',
  'Heart',
  'Home',
  'House',
  'Landmark',
  'Medal',
  'Package',
  'PackageOpen',
  'Percent',
  'PiggyBank',
  'Plane',
  'Shield',
  'ShieldCheck',
  'Sparkles',
  'Tent',
  'TrendingUp',
  'Trophy',
  'Umbrella',
  'Wallet',
  'WalletCards',
].sort()

export const ALLOCATION_DEFAULT_ICON = 'PiggyBank'
